# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest


variables:
- group: vercel-secrets 

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    PathtoPublish: 'build'        # 要发布的本地目录
    ArtifactName: 'drop'          # 给这个 artifact 起个名字（如 drop, www, dist）
    publishLocation: 'Container'  # 存到 Azure Pipelines 的存储（默认）

- script: |
    npm install -g vercel@latest
    vercel --version
  displayName: 'Install Vercel CLI'

- script: |
    echo "Deploying to Vercel..."
    vercel --token $(VERCEL_TOKEN) --prod --yes
  displayName: 'Deploy to Vercel'

  env:
    VERCEL_TOKEN: $(VERCEL_TOKEN)
